name: CI

on: 
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  workflow_dispatch:

jobs:

  build: 
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Swiftlint
        run: brew install swiftlint

      - name: Run SwifLint
        run: swiftlint

      - name: Build and test 
        run: cd CI-CD; xcodebuild clean build -scheme CI-CD -destination "platform=iOS Simulator,name=iPhone 14,OS=16.2" CODE_SIGNING_ALLOWED=NO
    
