name: CI

on: 
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  workflow_dispatch:

jobs:

  build: 
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Swiftlint
        run: brew install swiftlint

      - name: Run SwifLint
        run: swiftlint

      - name: Build one
        run: | 
        set -o pipefail
        xcodebuild build \
        -scheme iOSGitHubActions \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        | xcpretty

      # - name: Build App
      #   run: cd CI-CD; xcodebuild -destination "platform=iOS Simulator,name=iPhone 14,OS=16.2" -scheme CI-CD build
    
