name: Pull Request Checks

on:
  pull_request:
    types: [opened, edited]

jobs:
  call-reusable-workflow:
    uses: GuilhermeGatto/reusable-pipeline-mobile/.github/workflows/validate-pull-request.yml@master
    with:
      pr_number: ${{ github.event.pull_request.number }}
      repo: ${{ github.repository }}
    secrets: $
