name: Push 

on: 
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  workflow_dispatch:

jobs:

  build: 
    runs-on: macOS-latest

    steps: 
      - uses: actions/checkout@v4

      - name: List Simulators
        run: xcrun simctl list

      - name: Build App
        run: xcodebuild -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" -scheme CI-CD SYMROOT="./CI-CD/" build
    
