name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Request Validation
      uses: GuilhermeGatto/reusable-pipeline-mobile/.github/workflows/validate-pull-request.yml@master