name: Push 

on: 
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  workflow_dispatch:

jobs:

  build: 
    runs-on: macOS-latest

    steps: 
      - uses: actions/checkout@v4

      - name: List Simulators
        run: xcrun simctl list
    
