name: Push 

on: 
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  workflow_dispatch:

jobs:

  build: 
    runs-on: macOS-latest

    steps: 
      - uses: actions/checkout@v4

      - name: List Simulators
        run: xcrun simctl list

      - name: Build App
        run: cd CI-CD; pwd; xcodebuild -allowProvisioningUpdates -destination "platform=iOS Simulator,name=iPhone 14,OS=16.2" -scheme CI-CD SYMROOT=".build" build
    
